expenses/project/expenses/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy
from .models import Expense, Category
from .views import ExpenseListView, CategoryListView


urlpatterns = [
    path('expense/list/',
         ExpenseListView.as_view(ordering=Expense._meta.ordering[0]),
         name='expense-list'),
    path('expense/create/',
         CreateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-create'),
    path('expense/<int:pk>/edit/',
         UpdateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-edit'),
    path('expense/<int:pk>/delete/',
         DeleteView.as_view(
            model=Expense,
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_delete.html'
         ),
         name='expense-delete'),

    path('category/list/',
         CategoryListView.as_view(),
         name='category-list'),
    path('category/create/',
         CreateView.as_view(
            model=Category,
            fields='__all__',
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_update.html'
         ),
         name='category-create'),
     path('category/<int:pk>/edit/',
         UpdateView.as_view(
            model=Category,
            fields='__all__',
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_update.html'
         ),
         name='category-edit'),
    path('category/<int:pk>/delete/',
         DeleteView.as_view(
            model=Category,
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_delete.html'
         ),
         name='category-delete'),
]

expenses/project/project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='expenses:expense-list'),
         name='dashboard'),
    path('expenses/',
         include(('expenses.urls', 'expenses'), namespace='expenses')),
]

expenses/project/expenses/models.py
import datetime
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ('name',)

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class Expense(models.Model):
    class Meta:
        ordering = ('-date', '-pk',)

    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)

    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    date = models.DateField(default=datetime.date.today, db_index=True)

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

class Monthly(models.Model):
    class Meta:
        ordering = ('-date', )

    date = models.DateField(default=datetime.date.today, db_index=True)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return f'{self.date} {self.amount}'

expenses/project/expenses/forms.py

from django import forms
from django.db.models import Count
from django.db.models import Sum, Value
from django.db.models.functions import Coalesce
from .models import Expense


class ExpenseSearchForm(forms.ModelForm):

    from_Date = forms.DateField()
    to_Date = forms.DateField()
    categories = forms.TypedMultipleChoiceField(choices = {object['category_id'] : object['category_name'] for object in Expense.objects.values('category_id').annotate(category_name=Coalesce('category__name', Value('-')))
        .order_by()
        })
        
    class Meta:
        model = Expense
        fields = ('name', )
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False
        self.fields['from_Date'].required = False
        self.fields['to_Date'].required = False
        self.fields['categories'].required = False
        

        
        
        

expenses/project/expenses/views.py
from django.views.generic.list import ListView
from django.core.paginator import Paginator
from .forms import ExpenseSearchForm
from .models import Expense, Category, Monthly
from .reports import summary_per_category, summary_per_month, quantity_per_category
import json


class ExpenseListView(ListView):
    model = Expense
    paginate_by = 5
   
    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list
        
        form = ExpenseSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get('name', '').strip()
            from_Date = form.cleaned_data.get('from_Date', None)
            to_Date = form.cleaned_data.get('to_Date', None)
            categories = form.cleaned_data.get('categories', None)
            if name:
                queryset = queryset.filter(name__icontains=name)
            if from_Date:
                queryset = queryset.filter(date__range=[from_Date, queryset.order_by('date').last().date])
            if to_Date:
                queryset = queryset.filter(date__range=[queryset.order_by('date').first().date, to_Date])
            if categories:        
                queryset = queryset.filter(category_id__in=categories)
            if 'ordering' in self.request.GET:
                queryset = queryset.order_by(self.request.GET['ordering'], '-id')            
        return super().get_context_data(
            form=form,
            object_list=queryset,
            summary_per_category=summary_per_category(queryset)[0],
            Total=summary_per_category(queryset)[1],
            summary_per_month=summary_per_month(queryset),
            **kwargs)

class CategoryListView(ListView):
    model = Category
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = Expense.objects.all()
        object_list = self.object_list
        return super().get_context_data(
            object_list=object_list,
            quantity_per_category=quantity_per_category(queryset),
            **kwargs
        )

expenses/project/expenses/templates/expenses/category_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'expenses:category-create' %}">add</a>

<table border="1">
	<thead>
		<tr>
			<th>name</th>
			<th>quantity</th>
			<th>actions</th>
		</tr>
	</thead>
	<tbody>
		{% for obj in object_list %}
		<tr>
			<td>
				{{obj.name}}
			</td>
			<td>
				{% for category, quantity in quantity_per_category.items %}
					{% if category == obj.name and quantity != ' ' %}
						{{quantity}}
					{% endif %}
				{% endfor %}
			</td>
			<td>
				<a href="{% url 'expenses:category-delete' obj.id %}">delete</a>
				<a href="{% url 'expenses:category-edit' obj.id %}">edit</a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

expenses/project/expenses/templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'expenses:expense-create' %}">add</a>

<form method="get" action="">
  {{form.as_p}}
  <button type="submit">search</button>
  <br>
  <br>
  Sort by:
  <br>
  Date <button name="ordering" type="submit" value="date">\/</button>  <button name="ordering" type="submit" value="-date">/\</button>
  Category <button name="ordering" type="submit" value="category_id">\/</button>  <button name="ordering" type="submit" value="-category_id">/\</button>
</form>
<br>
<table border="1">
	<caption>Expenses</caption>
	<thead>
	  <tr>
		<th>no.</th>
		<th>category</th>
		<th>name</th>
		<th>amount</th>
		<th>date</th>
		<th>actions</th>
	  </tr>
	</thead>
	<tbody>

	{% for obj in object_list %}
	  <tr>
		<td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
		<td>{{ obj.category|default:"-" }}</td>
		<td>{{ obj.name|default:"-" }}</td>
		<td>{{ obj.amount|floatformat:2 }}</td>
		<td>{{obj.date}}</td>
		<td>
		  <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
		  <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
		</td>
	  </tr>
	  {% empty %}
	  <tr>
		<td colspan="5">no items</td>
	  </tr>
	{% endfor %}
	</tbody>
</table>

{% include "_pagination.html" %}
<hr>
<table border="1">
  <caption>Summary per category</caption>
  <tr>
    {% for category, total in summary_per_category.items %}
	<tr>
		<td>{{category}}:</td>
		<td>{{total|floatformat:2}}{{total|floatformat:2|json_script:'total'}}</td>
	</tr>
	{% endfor %}
	<tr>
		<td>Total:</td>
		<td id>{{Total|floatformat:2}}</td>
	</tr>
  </tr>
</table>

{% include "_pagination.html" %}
<hr>
<table border="1">
  <caption>Summary per year-month</caption>
  <tr>
	<script>var Total = 0</script>
    {% for year, month, total in summary_per_month %}
	<tr>
		<td>{{year}}-{{month}}:</td>
		<td>{{total|floatformat:2}}</td>
	</tr>
	{% endfor %}
  </tr>
</table>
{% endblock %}

expenses/project/project/templates/_pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

expenses/project/project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Expenses app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
	<a href="{% url 'expenses:expense-list' %}">Expenses</a> | 
	<a href="{% url 'expenses:category-list' %}">Categories</a> | 
	<hr>
    {% block content %}{% endblock %}
  </body>
</html>

expenses/project/project/templates/generic_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

expenses/project/project/templates/generic_update.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}